export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FILTER_MOVIE = 'FILTER_MOVIE';
export const FILTER_GAME = 'FILTER_GAME';
export const FILTER_SERIES = 'FILTER_SERIES';
export const FILTER_EPISODE = 'FILTER_EPISODE';
export const FILTER_YEAR = 'FILTER_YEAR';
export const FILTER_POSTER = 'FILTER_POSTER';
